In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 100)

In [4]:
df = pd.read_csv('support2.csv', index_col=None)
df

,age,death,sex,hospdead,slos,d.time,dzgroup,dzclass,num.co,edu,income,scoma,charges,totcst,totmcst,avtisst,race,sps,aps,surv2m,surv6m,hday,diabetes,dementia,ca,prg2m,prg6m,dnr,dnrday,meanbp,wblc,hrt,resp,temp,pafi,alb,bili,crea,sod,ph,glucose,bun,urine,adlp,adls,sfdm2,adlsc
1,62.84998,0,male,0,5,2029,Lung Cancer,Cancer,0,11.0,$11-$25k,0.0,9715.0,NaN,NaN,7.000000,other,33.898438,20.0,0.262939,0.036995,1,0,0,metastatic,0.50,0.250,no dnr,5.0,97.0,6.000000,69.0,22.0,36.00000,388.00000,1.799805,0.199982,1.199951,141.0,7.459961,NaN,NaN,NaN,7.0,7.0,NaN,7.000000
2,60.33899,1,female,1,4,4,Cirrhosis,COPD/CHF/Cirrhosis,2,12.0,$11-$25k,44.0,34496.0,NaN,NaN,29.000000,white,52.695312,74.0,0.001000,0.000000,3,0,0,no,0.00,0.000,NaN,NaN,43.0,17.097656,112.0,34.0,34.59375,98.00000,NaN,NaN,5.500000,132.0,7.250000,NaN,NaN,NaN,NaN,1.0,<2 mo. follow-up,1.000000
3,52.74698,1,female,0,17,47,Cirrhosis,COPD/CHF/Cirrhosis,2,12.0,under $11k,0.0,41094.0,NaN,NaN,13.000000,white,20.500000,45.0,0.790894,0.664917,4,0,0,no,0.75,0.500,no dnr,17.0,70.0,8.500000,88.0,28.0,37.39844,231.65625,NaN,2.199707,2.000000,134.0,7.459961,NaN,NaN,NaN,1.0,0.0,<2 mo. follow-up,0.000000
4,42.38498,1,female,0,3,133,Lung Cancer,Cancer,2,11.0,under $11k,0.0,3075.0,NaN,NaN,7.000000,white,20.097656,19.0,0.698975,0.411987,1,0,0,metastatic,0.90,0.500,no dnr,3.0,75.0,9.099609,88.0,32.0,35.00000,NaN,NaN,NaN,0.799927,139.0,NaN,NaN,NaN,NaN,0.0,0.0,no(M2 and SIP pres),0.000000
5,79.88495,0,female,0,16,2029,ARF/MOSF w/Sepsis,ARF/MOSF,1,NaN,NaN,26.0,50127.0,NaN,NaN,18.666656,white,23.500000,30.0,0.634888,0.532959,3,0,0,no,0.90,0.900,no dnr,16.0,59.0,13.500000,112.0,20.0,37.89844,173.31250,NaN,NaN,0.799927,143.0,7.509766,NaN,NaN,NaN,NaN,2.0,no(M2 and SIP pres),2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9101,66.07300,0,male,0,23,350,ARF/MOSF w/Sepsis,ARF/MOSF,1,8.0,NaN,0.0,52870.0,34329.3125,32042.7500,20.333328,white,16.296875,22.0,0.852905,0.801880,13,0,0,no,0.80,0.512,no dnr,23.0,109.0,7.399414,104.0,22.0,35.69531,280.00000,3.699707,0.399963,1.099854,131.0,7.459961,188.0,21.0,NaN,NaN,0.0,NaN,0.000000
9102,55.15399,0,female,0,29,347,Coma,Coma,1,11.0,NaN,41.0,35377.0,23558.5000,22131.0469,18.000000,white,25.796875,31.0,0.553955,0.485962,1,0,0,no,0.50,0.500,no dnr,29.0,43.0,NaN,0.0,8.0,38.59375,218.50000,NaN,NaN,5.899414,135.0,7.289062,190.0,49.0,0.0,NaN,0.0,NaN,0.000000
9103,70.38196,0,male,0,8,346,ARF/MOSF w/Sepsis,ARF/MOSF,1,NaN,NaN,0.0,46564.0,31409.0156,31131.2500,23.000000,white,22.699219,39.0,0.741943,0.660889,18,0,0,no,0.90,0.800,no dnr,8.0,111.0,8.398438,83.0,24.0,36.69531,180.00000,NaN,0.399963,2.699707,139.0,7.379883,189.0,60.0,3900.0,NaN,NaN,NaN,2.525391
9104,47.01999,1,male,1,7,7,MOSF w/Malig,ARF/MOSF,1,13.0,NaN,0.0,58439.0,NaN,NaN,35.500000,white,40.195312,51.0,0.177979,0.091995,22,0,0,yes,0.09,0.090,dnr after sadm,5.0,99.0,7.599609,110.0,24.0,36.39844,428.56250,1.199951,0.399963,3.500000,135.0,7.469727,246.0,55.0,NaN,NaN,0.0,<2 mo. follow-up,0.000000
9105,81.53894,1,female,0,12,198,ARF/MOSF w/Sepsis,ARF/MOSF,1,8.0,$11-$25k,0.0,15604.0,10605.7578,12146.1562,13.500000,white,18.097656,7.0,0.832886,0.776978,1,1,0,no,NaN,NaN,no dnr,12.0,75.0,8.599609,69.0,24.0,36.19531,230.40625,4.500000,0.599976,1.199951,137.0,7.289062,187.0,15.0,NaN,0.0,NaN,no(M2 and SIP pres),0.494751

In [5]:
df.describe()

,age,death,hospdead,slos,d.time,num.co,edu,scoma,charges,totcst,totmcst,avtisst,sps,aps,surv2m,surv6m,hday,diabetes,dementia,prg2m,prg6m,dnrday,meanbp,wblc,hrt,resp,temp,pafi,alb,bili,crea,sod,ph,glucose,bun,urine,adlp,adls,adlsc
count,9105.000000,9105.000000,9105.000000,9105.000000,9105.000000,9105.000000,7471.000000,9104.000000,8.933000e+03,8217.000000,5630.000000,9023.000000,9104.000000,9104.000000,9104.000000,9104.000000,9105.000000,9105.000000,9105.000000,7456.000000,7472.000000,9075.000000,9104.000000,8893.000000,9104.000000,9104.000000,9104.000000,6780.000000,5733.000000,6504.000000,9038.000000,9104.000000,6821.000000,4605.000000,4753.000000,4243.000000,3464.000000,6238.000000,9105.000000
mean,62.650823,0.681054,0.259198,17.863042,478.449863,1.868644,11.747691,12.058546,5.999579e+04,30825.867768,28828.877838,22.610928,25.525872,37.597979,0.635870,0.520096,4.400000,0.195277,0.032510,0.618769,0.499679,14.582590,84.546408,12.347677,97.156711,23.330294,37.103341,239.529070,2.950520,2.554463,1.770961,137.568541,7.415364,159.873398,32.349463,2191.546047,1.157910,1.637384,1.888272
std,15.593710,0.466094,0.438219,22.006440,560.383272,1.344409,3.447743,24.636694,1.026488e+05,45780.820986,43604.261932,13.233248,9.899377,19.903852,0.248175,0.253343,9.126811,0.396436,0.177359,0.298367,0.304367,19.944216,27.687692,9.266329,31.559292,9.573801,1.251796,109.665593,0.875944,5.318448,1.686041,6.029326,0.080563,88.391541,26.792288,1455.245777,1.739672,2.231358,2.003763
min,18.041990,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,0.000000,1.169000e+03,0.000000,-102.719970,1.000000,0.199982,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,-88.000000,0.000000,0.000000,0.000000,0.000000,31.699220,12.000000,0.399963,0.099991,0.099991,110.000000,6.829102,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,52.797000,0.000000,0.000000,6.000000,26.000000,1.000000,10.000000,0.000000,9.740000e+03,5929.566400,5177.404300,12.000000,19.000000,23.000000,0.507690,0.342957,1.000000,0.000000,0.000000,0.500000,0.200000,4.000000,63.000000,7.000000,72.000000,18.000000,36.195310,155.093750,2.399902,0.500000,0.899902,134.000000,7.379883,103.000000,14.000000,1165.500000,0.000000,0.000000,0.000000
50%,64.856990,1.000000,0.000000,11.000000,233.000000,2.000000,12.000000,0.000000,2.502400e+04,14452.734400,13223.500000,19.500000,23.898438,34.000000,0.715942,0.574951,1.000000,0.000000,0.000000,0.700000,0.500000,9.000000,77.000000,10.599609,100.000000,24.000000,36.695310,224.000000,2.899902,0.899902,1.199951,137.000000,7.419922,135.000000,23.000000,1968.000000,0.000000,1.000000,1.000000
75%,73.998960,1.000000,1.000000,20.000000,761.000000,3.000000,14.000000,9.000000,6.459800e+04,36087.937500,34223.601600,31.666656,30.199219,49.000000,0.825928,0.725952,3.000000,0.000000,0.000000,0.900000,0.750000,17.000000,107.000000,15.298828,120.000000,28.000000,38.195310,304.750000,3.599609,1.899902,1.899902,141.000000,7.469727,188.000000,42.000000,3000.000000,2.000000,3.000000,3.000000
max,101.847960,1.000000,1.000000,343.000000,2029.000000,9.000000,31.000000,100.000000,1.435423e+06,633212.000000,710682.000000,83.000000,99.187500,143.000000,0.969971,0.947998,148.000000,1.000000,1.000000,1.000000,1.000000,285.000000,195.000000,200.000000,300.000000,90.000000,41.695310,890.375000,29.000000,63.000000,21.500000,181.000000,7.769531,1092.000000,300.000000,9000.000000,7.000000,7.000000,7.073242

## Note
If don't want to use previous model, be sure not to use aps, sps, surv2m, surv6m as predictors. You also will probably not want to use prg2m, prg6m, dnr, dnrday.

## Preprocessing
- One-hot encode variable: sex(2), dzclass(4), race (5), ca(3), income(4), sfdm2 (5)
- Target variables: hospdead(0 / 1)
- Remove features: death (non-target), slos, d.time(related directly to outcome), dzgroup (similar to dzclass), charges, totcst, totmcst (cost not related), not to use previous model(aps, sps, surv2m, surv6m) and prg2m, prg6m, dnr, dnrday.

Total features: 47 + 17 - 16 = 48

In [6]:
one_hot_encode_cols = ['sex', 'dzclass', 'race' , 'ca', 'income', 'sfdm2']
target_variables = ['hospdead']
remove_features = ['death', 'slos', 'd.time', 'dzgroup', 'charges', 'totcst', 
                   'totmcst', 'aps', 'sps', 'surv2m', 'surv6m', 'prg2m', 'prg6m', 'dnr', 'dnrday']

In [7]:
df = df.drop(remove_features, axis=1)
df.shape

(9105, 32)

In [8]:
rest_colmns = [c for c in df.columns if c not in (one_hot_encode_cols + target_variables)]
df[rest_colmns].describe()

,age,num.co,edu,scoma,avtisst,hday,diabetes,dementia,meanbp,wblc,hrt,resp,temp,pafi,alb,bili,crea,sod,ph,glucose,bun,urine,adlp,adls,adlsc
count,9105.000000,9105.000000,7471.000000,9104.000000,9023.000000,9105.000000,9105.000000,9105.000000,9104.000000,8893.000000,9104.000000,9104.000000,9104.000000,6780.000000,5733.000000,6504.000000,9038.000000,9104.000000,6821.000000,4605.000000,4753.000000,4243.000000,3464.000000,6238.000000,9105.000000
mean,62.650823,1.868644,11.747691,12.058546,22.610928,4.400000,0.195277,0.032510,84.546408,12.347677,97.156711,23.330294,37.103341,239.529070,2.950520,2.554463,1.770961,137.568541,7.415364,159.873398,32.349463,2191.546047,1.157910,1.637384,1.888272
std,15.593710,1.344409,3.447743,24.636694,13.233248,9.126811,0.396436,0.177359,27.687692,9.266329,31.559292,9.573801,1.251796,109.665593,0.875944,5.318448,1.686041,6.029326,0.080563,88.391541,26.792288,1455.245777,1.739672,2.231358,2.003763
min,18.041990,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,31.699220,12.000000,0.399963,0.099991,0.099991,110.000000,6.829102,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,52.797000,1.000000,10.000000,0.000000,12.000000,1.000000,0.000000,0.000000,63.000000,7.000000,72.000000,18.000000,36.195310,155.093750,2.399902,0.500000,0.899902,134.000000,7.379883,103.000000,14.000000,1165.500000,0.000000,0.000000,0.000000
50%,64.856990,2.000000,12.000000,0.000000,19.500000,1.000000,0.000000,0.000000,77.000000,10.599609,100.000000,24.000000,36.695310,224.000000,2.899902,0.899902,1.199951,137.000000,7.419922,135.000000,23.000000,1968.000000,0.000000,1.000000,1.000000
75%,73.998960,3.000000,14.000000,9.000000,31.666656,3.000000,0.000000,0.000000,107.000000,15.298828,120.000000,28.000000,38.195310,304.750000,3.599609,1.899902,1.899902,141.000000,7.469727,188.000000,42.000000,3000.000000,2.000000,3.000000,3.000000
max,101.847960,9.000000,31.000000,100.000000,83.000000,148.000000,1.000000,1.000000,195.000000,200.000000,300.000000,90.000000,41.695310,890.375000,29.000000,63.000000,21.500000,181.000000,7.769531,1092.000000,300.000000,9000.000000,7.000000,7.000000,7.073242

In [9]:
# Normalize to 0 mean 1 std
df[rest_colmns] = df[rest_colmns].apply(lambda x: (x - x.mean()) / x.std())
# Cap the value to +-3
df.loc[:, rest_colmns][df.loc[:, rest_colmns] > 3.] = 3.
df.loc[:, rest_colmns][df.loc[:, rest_colmns] < -3.] = -3.
# Impute the missing values for 0.
df[rest_colmns] = df[rest_colmns].fillna(0.)

In [10]:
# Handle binary attributes
df = pd.get_dummies(df, prefix=one_hot_encode_cols)

In [11]:
df.head()

,age,hospdead,num.co,edu,scoma,avtisst,hday,diabetes,dementia,meanbp,wblc,hrt,resp,temp,pafi,alb,bili,crea,sod,ph,glucose,bun,urine,adlp,adls,adlsc,sex_female,sex_male,dzclass_ARF/MOSF,dzclass_COPD/CHF/Cirrhosis,dzclass_Cancer,dzclass_Coma,race_$11-$25k,race_$25-$50k,race_>$50k,race_under $11k,ca_asian,ca_black,ca_hispanic,ca_other,ca_white,income_metastatic,income_no,income_yes,sfdm2_<2 mo. follow-up,sfdm2_Coma or Intub,sfdm2_SIP>=30,sfdm2_adl>=4 (>=5 if sur),sfdm2_no(M2 and SIP pres)
1,0.012772,0,-1.389937,-0.216864,-0.489455,-1.179675,-0.372529,-0.492582,-0.183298,0.449788,-0.685026,-0.892185,-0.138952,-0.881407,1.353852,-1.313685,-0.442701,-0.338669,0.569128,0.553561,0.0,0.0,0.0,3.358157,2.403297,2.551065,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
2,-0.148254,1,0.097706,0.073181,1.296499,0.482804,-0.153394,-0.492582,-0.183298,-1.500537,0.512606,0.470330,1.114469,-2.004793,-1.290551,0.000000,0.000000,2.211713,-0.923576,-2.052594,0.0,0.0,0.0,0.000000,-0.285648,-0.443302,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0
3,-0.635118,0,0.097706,0.073181,-0.489455,-0.726271,-0.043827,-0.492582,-0.183298,-0.525375,-0.415232,-0.290143,0.487759,0.235741,-0.071789,0.000000,-0.066703,0.135844,-0.591864,0.553561,0.0,0.0,0.0,-0.090770,-0.733806,-0.942363,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0
4,-1.299617,0,0.097706,-0.216864,-0.489455,-1.179675,-0.372529,-0.492582,-0.183298,-0.344789,-0.350524,-0.290143,0.905566,-1.680259,0.000000,0.000000,0.000000,-0.575925,0.237416,0.000000,0.0,0.0,0.0,-0.665591,-0.733806,-0.942363,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1
5,1.105197,0,-0.646115,0.000000,0.565882,-0.298058,-0.153394,-0.492582,-0.183298,-0.922663,0.124356,0.470330,-0.347855,0.635167,-0.603804,0.000000,0.000000,-0.575925,0.900840,1.171770,0.0,0.0,0.0,0.000000,0.162509,0.055759,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1

In [12]:
x = df.drop(['hospdead'], axis=1)
y = df[['hospdead']]

In [13]:
x.to_csv('x.csv', index=None)
y.to_csv('y.csv', index=None)

In [20]:
x.shape

(9105, 48)

In [25]:
x.columns[[3, 4, 39, 43, 47]]

Index(['scoma', 'avtisst', 'ca_white', 'sfdm2_<2 mo. follow-up',
       'sfdm2_no(M2 and SIP pres)'],
      dtype='object')

## 1/10 Record
- Find the accuracy too high and caused by following features ['scoma', 'avtisst', 'ca_white', 'sfdm2_<2 mo.follow-up', 'sfdm2_no(M2 and SIP pres)']
- Remove avtisst and sfdm2 (since they all need to know the future)

In [14]:
one_hot_encode_cols = ['sex', 'dzclass', 'race' , 'ca', 'income']
target_variables = ['hospdead']
remove_features = ['death', 'slos', 'd.time', 'dzgroup', 'charges', 'totcst', 
                   'totmcst', 'aps', 'sps', 'surv2m', 'surv6m', 'prg2m', 'prg6m', 'dnr', 'dnrday', 'avtisst', 'sfdm2']

In [16]:
df = pd.read_csv('support2.csv', index_col=None)
df = df.drop(remove_features, axis=1)
df.shape

(9105, 30)

In [17]:
rest_colmns = [c for c in df.columns if c not in (one_hot_encode_cols + target_variables)]
# Normalize to 0 mean 1 std
df[rest_colmns] = df[rest_colmns].apply(lambda x: (x - x.mean()) / x.std())
# Cap the value to +-3
df.loc[:, rest_colmns][df.loc[:, rest_colmns] > 3.] = 3.
df.loc[:, rest_colmns][df.loc[:, rest_colmns] < -3.] = -3.
# Impute the missing values for 0.
df[rest_colmns] = df[rest_colmns].fillna(0.)

In [18]:
# Handle binary attributes
df = pd.get_dummies(df, prefix=one_hot_encode_cols)

In [20]:
x = df.drop(['hospdead'], axis=1)
y = df[['hospdead']]

In [21]:
x.to_csv('x_new.csv', index=None)
y.to_csv('y_new.csv', index=None)

## Add another prediction task for the slos

In [33]:
df2 = pd.DataFrame.from_csv('support2.csv', index_col=None)

/home/zzzace2000/anaconda2/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

In [35]:
y = df2[['slos']]
y.head()

   slos
1     5
2     4
3    17
4     3
5    16

In [36]:
y.to_csv('y_new_slos.csv', index=None)